version: '3.1'
services:
  gitlab:
    image: 'twang2218/gitlab-ce-zh:11.1.4'
    container_name: "gitlab"
    restart: always
    privileged: true
    hostname: 'gitlab'
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1'   # 配置当前服务器ip
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '8088:80'
      - '2443:443'
      - '2222:22'
    volumes:
      - /Users/pm/coding/docker.compose/gitlab/opt/gitlab/config:/etc/gitlab
      - /Users/pm/coding/docker.compose/gitlab/opt/gitlab/data:/var/opt/gitlab
      - /Users/pm/coding/docker.compose/gitlab/opt/gitlab/logs:/var/log/gitlab
