version: '2'
services:
  gitlab:
    image: 'twang2218/gitlab-ce-zh:11.1.4'
    container_name: "gitlab"
    restart: unless-stopped
    privileged: true
    hostname: 'gitlab'
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://0.0.0.0'
        gitlab_rails['time_zone'] = 'Asia/Shanghai's
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.aliyun.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "xujiantong@aliyun.com"  #用自己的aliyun邮箱
        gitlab_rails['smtp_password'] = "Asilence31"
        gitlab_rails['smtp_domain'] = "aliyun.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_from'] = 'xujiantong@aliyun.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '8088:80'
      - '2443:443'
      - '2222:22'
    volumes:
      - /Users/pm/coding/docker.compose/gitlab/opt/gitlab/config:/etc/gitlab
      - /Users/pm/coding/docker.compose/gitlab/opt/gitlab/data:/var/opt/gitlab
      - /Users/pm/coding/docker.compose/gitlab/opt/gitlab/logs:/var/log/gitlab
