version: '3'
services:
  nginx:
    image: nginx
      restart: always
      container_name: nginx
      environment:
        - TZ=Asia/Shanghai
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./log:/var/log/nginx
        - ./html:/html
        - /etc/letsencrypt:/etc/letsencrypt

